### ISSUE TITLE
Display sign languages in Sutton Signwriting

### ISSUE THREAD

**Issue by loominade** [envlh/dicare-tools#11]
There are more and more lexemes written in FSW signwriting which is (I guess) hardly readably and it blows the layout of the table. I think you can convert [all these languages](https://w.wiki/6N$n) to [sutton signwriting](https://steveslevinski.me/demo/fsw.html) which consumes much less space and is prettier to look at 😬.

There is an [excellent library](https://github.com/sutton-signwriting/font-ttf) to do that, written in Javascript.

**Comment by envlh** [comment]
I started to dig in this issue. Thanks a lot for the idea :)

With this code:

```
<style type="text/css">
@font-face {
  font-family: "SuttonSignWriting";
  src: url("https://slevinski.github.io/SuttonSignWriting/assets/SuttonSignWritingOneD.ttf");
}
.sutton { font-family: SuttonSignWriting, sans-serif; font-size: 20px; }
</style>

<script src="https://unpkg.com/@sutton-signwriting/core@1.5.7"></script>
<script type="text/javascript">
Array.from(document.getElementsByClassName('sutton')).forEach((element) => {
    element.innerHTML = ssw.core.convert.fsw2swu(element.innerHTML);
});
</script>
```

I have something like this:

![image](https://github.com/envlh/dicare-tools/assets/6069282/bce53d5d-27a6-43b2-99e2-8c42ffa04d3a)

~~Do you have an idea on how this can be improved?~~ Never mind, I handled it with sutton-signwriting/font-ttf. I'll let you know when it is usable.

**Comment by envlh** [comment]
It's done! https://github.com/envlh/dicare-tools/commit/c0d4bef9849fdc33c5f58d4ac4ab18ce42bc4ec6

Example: https://dicare.toolforge.org/lexemes/challenge.php?id=5

Thanks again for the idea :)

Don't hesitate to get in touch with me if it needs some tweaking.
