### ISSUE TITLE
Please provide predictable permalinks in wikidata-diff

### ISSUE THREAD

**Issue by pigsonthewing** [envlh/dicare-tools#2]
A URL for each comparison should be available, such that we can predict it once we know two QIDs. 

For example when comparing Q15136093 & Q4911143, the URL would be, say:

`http://tools.dicare.org/wikidata-diff/Q15136093+Q4911143`

or:

`http://tools.dicare.org/wikidata-diff/&a=Q15136093&b=Q4911143`

**Comment by envlh** [comment]
Thanks :)

Done, with URL like this:
http://tools.dicare.org/wikidata-diff/?qids=Q142+Q183&language=br

Note that you still have to click on _Compare_ after using the link to display the comparison.
