### ISSUE TITLE
↑ arrow displaced on narrow viewport

### ISSUE THREAD

**Issue by fuddl** [envlh/dicare-tools#4]
![E7EB61C3-DED6-40DA-9B97-DD21C5E85EC6](https://user-images.githubusercontent.com/842548/148787176-cb877a37-2e24-47d0-9b36-746be2e481db.png)

i recommend not to use float in such situations. A separate column would solve the problem

**Comment by envlh** [comment]
Hi! Thank you for the feedback.

I implemented the solution you proposed. I also added a link in the main table, so every language can be easily linked.

In both cases, the link is displayed only when the mouse is hover the row (for devices that don't support hovering, the link is always displayed).

Let me know what you think (and don't forget to clear the cache of your web browser ^^).

**Comment by fuddl** [comment]
👌
